version: "3"

services:
  api:
    build: ./vtrack_api
    command: gunicorn vtrack.wsgi:application --chdir=/vtrack/src -b=0.0.0.0:8000 -w=4 -t=10
    container_name: "vTrack-Backend"
    environment:
      VTRACK_ENV: ${VTRACK_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: vtrack:api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./vtrack_api:/vtrack
      
  webui:
    build: ./vtract_webui
    command: bash -c "npm run build && npm start"
    container_name: "vTrack-Frontend"
    environment:
      NODE_ENV: ${NODE_ENV:-local}
    image: vtrack:webui
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./vtract_webui:/vtrack
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: "vTrack-Nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./vtrack_api/static:/static
      - ./vtrack_api/media:/media
      - ./vtrack_webui/.next:/.next
    depends_on:
      - webui
